# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2022 Sebastian Crane <seabass-labrax@gmx.com>

name: Check for DCO sign-off messages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  dco:
    name: Check for DCO sign-off messages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dco-check
        run: sudo apt install -y python3-pip && pip install dco-check
      - name: Run `dco-check`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: dco-check
